name: eve_flashcards
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 4.0.6
  shared_preferences: 2.0.15
  flutter_svg: 1.1.4
  url_launcher: 6.1.5
  package_info_plus: 1.4.3+1
  connectivity_plus: 2.3.6+1
  animated_text_kit: 4.2.2
  showcaseview: 1.1.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: LuckiestGuy
      fonts: 
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
  assets: 
    - assets/images/
    - assets/locales/
  uses-material-design: true

